name: Howard integration workflow
on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
jobs:
  markdown-check:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@main
    with:
      md-lint-config-file-path: .markdownlint.json

  yaml-check:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-yaml-check.yml@main
  repo-standard:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit
